export const userTasks = [
    {
        id: 0,
        title: "Do Math Homework",
        description: "Complete algebra homework from 2 to 5",
        taskDate: '2024-10-01',
        taskHour: 16,
        taskMinute: 45,
        taskPriority: 1,
        taskCategory: 'Work',
        color: '#ff9680',
        image: require('.././assets/images/Category/briefcase.png'),
        isCompleted: 0,
    },
    {
        id: 1,
        title: "Buy Groceries",
        description: "Pick up vegetables and fruits from the store",
        taskDate: '2024-10-01',
        taskHour: 10,
        taskMinute: 30,
        taskPriority: 2,
        taskCategory: 'Grocery',
        color: '#ccff80',
        image: require('.././assets/images/Category/bread.png'),
        isCompleted: 1
    },
    {
        id: 2,
        title: "Go for a Run",
        description: "Run 5 km in the park",
        taskDate: '2024-10-01',
        taskHour: 7,
        taskMinute: 0,
        taskPriority: 1,
        taskCategory: 'Sport',
        color: '#80ffff',
        image: require('.././assets/images/Category/sport.png'),
        isCompleted: 0
    },
    {
        id: 3,
        title: "UI Design Project",
        description: "Work on the homepage design for the client",
        taskDate: '2024-10-02',
        taskHour: 14,
        taskMinute: 0,
        taskPriority: 3,
        taskCategory: 'Design',
        color: '#80ffd9',
        image: require('.././assets/images/Category/design.png'),
        isCompleted: 0
    },
    {
        id: 4,
        title: "Study for Midterm",
        description: "Review chapters 3 and 4 for the upcoming exam",
        taskDate: '2024-10-03',
        taskHour: 18,
        taskMinute: 0,
        taskPriority: 1,
        taskCategory: 'University',
        color: '#809cff',
        image: require('.././assets/images/Category/mortarboard.png'),
        isCompleted: 0
    },
    {
        id: 5,
        title: "Attend Friend's Birthday Party",
        description: "Join the celebration at 6 PM",
        taskDate: '2024-10-05',
        taskHour: 18,
        taskMinute: 0,
        taskPriority: 2,
        taskCategory: 'Social',
        color: '#ff80eb',
        image: require('.././assets/images/Category/megaphone.png'),
        isCompleted: 1
    },
    {
        id: 6,
        title: "Practice Guitar",
        description: "Learn new chords for the song",
        taskDate: '2024-10-06',
        taskHour: 19,
        taskMinute: 30,
        taskPriority: 2,
        taskCategory: 'Music',
        color: '#fc80ff',
        image: require('.././assets/images/Category/music.png'),
        isCompleted: 0
    },
    {
        id: 7,
        title: "Visit Doctor",
        description: "Regular health check-up",
        taskDate: '2024-10-07',
        taskHour: 9,
        taskMinute: 0,
        taskPriority: 1,
        taskCategory: 'Health',
        color: '#80ffa3',
        image: require('.././assets/images/Category/heartbeat.png'),
        isCompleted: 1
    },
    {
        id: 8,
        title: "Watch a Movie",
        description: "Watch the latest action movie",
        taskDate: '2024-10-08',
        taskHour: 20,
        taskMinute: 0,
        taskPriority: 3,
        taskCategory: 'Movie',
        color: '#80d1ff',
        image: require('.././assets/images/Category/video-camera.png'),
        isCompleted: 0
    },
    {
        id: 9,
        title: "Clean the House",
        description: "Organize the living room and kitchen",
        taskDate: '2024-10-09',
        taskHour: 11,
        taskMinute: 30,
        taskPriority: 2,
        taskCategory: 'Home',
        color: '#ffcc80',
        image: require('.././assets/images/Category/home.png'),
        isCompleted: 1
    },
    {
        id: 10,
        title: "Prepare Presentation",
        description: "Work on slides for Monday's meeting",
        taskDate: '2024-10-10',
        taskHour: 14,
        taskMinute: 30,
        taskPriority: 1,
        taskCategory: 'Work',
        color: '#ff9680',
        image: require('.././assets/images/Category/briefcase.png'),
        isCompleted: 0
    },
    {
        id: 11,
        title: "Grocery Shopping",
        description: "Buy essentials: milk, bread, eggs",
        taskDate: '2024-10-11',
        taskHour: 9,
        taskMinute: 0,
        taskPriority: 2,
        taskCategory: 'Grocery',
        color: '#ccff80',
        image: require('.././assets/images/Category/bread.png'),
        isCompleted: 0
    },
    {
        id: 12,
        title: "Evening Yoga",
        description: "Relax with 30 minutes of yoga",
        taskDate: '2024-10-11',
        taskHour: 18,
        taskMinute: 30,
        taskPriority: 1,
        taskCategory: 'Sport',
        color: '#80ffff',
        image: require('.././assets/images/Category/sport.png'),
        isCompleted: 1
    },
    {
        id: 13,
        title: "Finalize Website Mockups",
        description: "Send final version of mockups to client",
        taskDate: '2024-10-12',
        taskHour: 13,
        taskMinute: 0,
        taskPriority: 1,
        taskCategory: 'Design',
        color: '#80ffd9',
        image: require('.././assets/images/Category/design.png'),
        isCompleted: 0
    },
    {
        id: 14,
        title: "Group Study Session",
        description: "Review physics with classmates",
        taskDate: '2024-10-13',
        taskHour: 15,
        taskMinute: 0,
        taskPriority: 2,
        taskCategory: 'University',
        color: '#809cff',
        image: require('.././assets/images/Category/mortarboard.png'),
        isCompleted: 0
    },
    {
        id: 15,
        title: "Movie Night with Friends",
        description: "Watch a comedy movie together",
        taskDate: '2024-10-14',
        taskHour: 20,
        taskMinute: 0,
        taskPriority: 3,
        taskCategory: 'Social',
        color: '#ff80eb',
        image: require('.././assets/images/Category/megaphone.png'),
        isCompleted: 0
    },
    {
        id: 16,
        title: "Learn a New Song",
        description: "Practice a new piece on the piano",
        taskDate: '2024-10-15',
        taskHour: 17,
        taskMinute: 0,
        taskPriority: 2,
        taskCategory: 'Music',
        color: '#fc80ff',
        image: require('.././assets/images/Category/music.png'),
        isCompleted: 0
    },
    {
        id: 17,
        title: "Daily Meditation",
        description: "Morning meditation for 15 minutes",
        taskDate: '2024-10-16',
        taskHour: 6,
        taskMinute: 30,
        taskPriority: 1,
        taskCategory: 'Health',
        color: '#80ffa3',
        image: require('.././assets/images/Category/heartbeat.png'),
        isCompleted: 1
    },
    {
        id: 18,
        title: "Watch a Documentary",
        description: "Catch up on the latest nature documentary",
        taskDate: '2024-10-17',
        taskHour: 21,
        taskMinute: 0,
        taskPriority: 3,
        taskCategory: 'Movie',
        color: '#80d1ff',
        image: require('.././assets/images/Category/video-camera.png'),
        isCompleted: 0
    },
    {
        id: 19,
        title: "Organize Closet",
        description: "Sort through old clothes and reorganize",
        taskDate: '2024-10-18',
        taskHour: 10,
        taskMinute: 0,
        taskPriority: 2,
        taskCategory: 'Home',
        color: '#ffcc80',
        image: require('.././assets/images/Category/home.png'),
        isCompleted: 1
    },
]